pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'enterprise-jvm-platform'

include 'apps:customer-api'
include 'apps:billing-api'
include 'apps:merchant-portal-api'
include 'apps:risk-api'
include 'services:ledger-service'
include 'services:notification-service'
include 'services:identity-service'
include 'services:feature-flag-service'
include 'workers:settlement-worker'
include 'workers:statement-export-worker'
include 'workers:chargeback-worker'
include 'libraries:common-domain'
include 'libraries:audit-events'
include 'libraries:security-jwt'
include 'libraries:observability'
include 'integrations:bank-core-adapter'
include 'integrations:salesforce-sync'
include 'integrations:email-delivery'
